In [6]:
url = r"C:\Users\princ\OneDrive\Documents\Chapter 1\Python\Machine Learning\ML Data\Calories Data\calories.csv"
URL = r"C:\Users\princ\OneDrive\Documents\Chapter 1\Python\Machine Learning\ML Data\Calories Data\Calories Data.csv"

Importing Dependencies

In [42]:
import numpy as mp
import pandas as pd
from sklearn.model_selection import cross_val_score

Data Loading and Preprocessing

In [8]:
#Loading the dataset to a pandas dataframe
data = pd.read_csv(url)
df = pd.read_csv(URL)

In [9]:
#Printing first five rows of the dataset
data.head()

    User_ID  Calories
0  14733363     231.0
1  14861698      66.0
2  11179863      26.0
3  16180408      71.0
4  17771927      35.0

In [11]:
df.head()

    User_ID  Gender  Age  Height  Weight  Duration  Heart_Rate  Body_Temp
0  14733363    male   68   190.0    94.0      29.0       105.0       40.8
1  14861698  female   20   166.0    60.0      14.0        94.0       40.3
2  11179863    male   69   179.0    79.0       5.0        88.0       38.7
3  16180408  female   34   179.0    71.0      13.0       100.0       40.5
4  17771927  female   27   154.0    58.0      10.0        81.0       39.8

In [20]:
#Now adding the both dataset in one dataset
df['Calories_Burnt'] = data['Calories']

In [21]:
df.head()

,User_ID,Gender,Age,Height,Weight,Duration,Heart_Rate,Body_Temp,Calories_Burnt
0,14733363,male,68,190.0,94.0,29.0,105.0,40.8,231.0
1,14861698,female,20,166.0,60.0,14.0,94.0,40.3,66.0
2,11179863,male,69,179.0,79.0,5.0,88.0,38.7,26.0
3,16180408,female,34,179.0,71.0,13.0,100.0,40.5,71.0
4,17771927,female,27,154.0,58.0,10.0,81.0,39.8,35.0

In [22]:
#Shape of dataset
df.shape

(15000, 9)

In [24]:
#Replacing the categorical column Gender woith numerical one
df['Gender'] = df['Gender'].replace({"male":0,"female":1})

C:\Users\princ\AppData\Local\Temp\ipykernel_14256\2183872161.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Gender'] = df['Gender'].replace({"male":0,"female":1})

In [25]:
df.head()

,User_ID,Gender,Age,Height,Weight,Duration,Heart_Rate,Body_Temp,Calories_Burnt
0,14733363,0,68,190.0,94.0,29.0,105.0,40.8,231.0
1,14861698,1,20,166.0,60.0,14.0,94.0,40.3,66.0
2,11179863,0,69,179.0,79.0,5.0,88.0,38.7,26.0
3,16180408,1,34,179.0,71.0,13.0,100.0,40.5,71.0
4,17771927,1,27,154.0,58.0,10.0,81.0,39.8,35.0

In [29]:
#Statistical measures of the data
df.describe()

,User_ID,Gender,Age,Height,Weight,Duration,Heart_Rate,Body_Temp,Calories_Burnt
count,1.500000e+04,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000
mean,1.497736e+07,0.503533,42.789800,174.465133,74.966867,15.530600,95.518533,40.025453,89.539533
std,2.872851e+06,0.500004,16.980264,14.258114,15.035657,8.319203,9.583328,0.779230,62.456978
min,1.000116e+07,0.000000,20.000000,123.000000,36.000000,1.000000,67.000000,37.100000,1.000000
25%,1.247419e+07,0.000000,28.000000,164.000000,63.000000,8.000000,88.000000,39.600000,35.000000
50%,1.499728e+07,1.000000,39.000000,175.000000,74.000000,16.000000,96.000000,40.200000,79.000000
75%,1.744928e+07,1.000000,56.000000,185.000000,87.000000,23.000000,103.000000,40.600000,138.000000
max,1.999965e+07,1.000000,79.000000,222.000000,132.000000,30.000000,128.000000,41.500000,314.000000

In [26]:
#Chcking for any missing values
df.isnull().sum()

User_ID           0
Gender            0
Age               0
Height            0
Weight            0
Duration          0
Heart_Rate        0
Body_Temp         0
Calories_Burnt    0
dtype: int64

In [27]:
#Checking correlation between the data
df.corr()

,User_ID,Gender,Age,Height,Weight,Duration,Heart_Rate,Body_Temp,Calories_Burnt
User_ID,1.000000,0.000687,-0.001827,-0.013520,-0.011603,-0.002751,-0.000457,0.000923,-0.001661
Gender,0.000687,1.000000,-0.003222,-0.710534,-0.783186,-0.003440,-0.011555,-0.007264,-0.022357
Age,-0.001827,-0.003222,1.000000,0.009554,0.090094,0.013247,0.010482,0.013175,0.154395
Height,-0.013520,-0.710534,0.009554,1.000000,0.958451,-0.004625,0.000528,0.001200,0.017537
Weight,-0.011603,-0.783186,0.090094,0.958451,1.000000,-0.001884,0.004311,0.004095,0.035481
Duration,-0.002751,-0.003440,0.013247,-0.004625,-0.001884,1.000000,0.852869,0.903167,0.955421
Heart_Rate,-0.000457,-0.011555,0.010482,0.000528,0.004311,0.852869,1.000000,0.771529,0.897882
Body_Temp,0.000923,-0.007264,0.013175,0.001200,0.004095,0.903167,0.771529,1.000000,0.824558
Calories_Burnt,-0.001661,-0.022357,0.154395,0.017537,0.035481,0.955421,0.897882,0.824558,1.000000

In [32]:
#Splitting the data into training and features data
X = df.drop(columns = ['Calories_Burnt','User_ID'],axis = 1)
Y = df['Calories_Burnt']

Importing Models

In [39]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
import xgboost as xgb

In [49]:
models = [LinearRegression(),DecisionTreeRegressor(max_depth = 5),RandomForestRegressor(n_estimators = 100,max_depth = 5),xgb.XGBRegressor(n_estimators = 100,learning_rate = 0.1,max_depth = 5)]

In [66]:
def commpare_model_cross_validation():
    for model in models:

        cv_score = cross_val_score(model,X,Y,cv = 5,scoring='r2')
        meeR2_score = round(sum(cv_score)/len(cv_score),2)

        print('Cross Validation R2_score for the ',model,'=',cv_score)

        print('R2_score of the ',model,'=',R2_score)
        
        print("---------------------------------------------------------------------------------")

In [67]:
commpare_model_cross_validation()

Cross Validation R2_score for the  LinearRegression() = [0.96712832 0.96658977 0.96769213 0.96828562 0.96606908]
R2_score of the  LinearRegression() = 0.97
---------------------------------------------------------------------------------
Cross Validation R2_score for the  DecisionTreeRegressor(max_depth=5) = [0.95882074 0.95999093 0.96056165 0.96184124 0.95970864]
R2_score of the  DecisionTreeRegressor(max_depth=5) = 0.96
---------------------------------------------------------------------------------
Cross Validation R2_score for the  RandomForestRegressor(max_depth=5) = [0.97415977 0.97377533 0.97471515 0.97299025 0.97461131]
R2_score of the  RandomForestRegressor(max_depth=5) = 0.97
---------------------------------------------------------------------------------
Cross Validation R2_score for the  XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...) = [0.99866621 0.99876299 0.99883319 0.99869018 0.99872924]
R2_score of the  XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...) = 1.0
---------------------------------------------------------------------------------

As we can see the Best model is XGBoost Regressor with Astonishing 99.87% Accuracy